-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE, 
 SUM(PRODUCT.PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT NATURAL JOIN OFFLINE_SALE
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT.PRODUCT_CODE ASC;
