SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW NATURAL JOIN MEMBER_PROFILE NATURAL JOIN 
    (
        SELECT MEMBER_ID, COUNT(MEMBER_ID) AS MCOUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY MCOUNT DESC LIMIT 1
    ) AS MTABLE
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
